### ISSUE TITLE
changing NSG cause the VNET to be re-created 

### ISSUE THREAD

**Issue by tradosh** [Azure/terraform-azurerm-vnet#51] opened 2021-07-13 14:04 UTC
if you update, or change the NSG the network get's recreated, that is not feasible if you have servers or other devices running on it

**Comment by carlosdoliveira** [comment] 2021-11-11 01:49
Could you show an example of how changing NSGs is affecting your vnet?

**Comment by holms** [comment] 2022-10-06 23:10
If this is true than this module is totally unusable, I'd better write my own then to avoid such problems.

**Comment by lonegunmanb** [comment] 2022-10-10 07:08
@a-z-i-z I'm curious is the `azurerm_network_security_rule` in your screenshot created by this module? Since I cannot find such resource definition in this vnet module. Would you please give me a minimum sample that can reproduce your issue step by step so I can try to fix it on my side? Thanks.

**Comment by a-z-i-z** [comment] 2022-10-10 07:33
@lonegunmanb I've used this VNet [module](https://registry.terraform.io/modules/Azure/vnet/azurerm/latest) and this NSG [module](https://registry.terraform.io/modules/Azure/network-security-group/azurerm/latest). I am not sure either NSG or VNet module is creating the re-creation issue but using both together creates a problem. Let me know if I can help you anyway on this.
Thanks.

**Comment by lonegunmanb** [comment] 2022-10-10 07:50
Folks I've tested on my side with the following sample:

```hcl
resource "random_id" "rg_name" {
  byte_length = 8
}

resource "azurerm_resource_group" "example" {
  location = var.location
  name     = "test-${random_id.rg_name.hex}-rg"
}

module "vnet" {
  source = "../../"

  resource_group_name = azurerm_resource_group.example.name
  address_space       = ["10.0.0.0/16"]
  subnet_prefixes     = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
  subnet_names        = ["subnet1", "subnet2", "subnet3"]

  nsg_ids = {
    subnet1 = azurerm_network_security_group.ssh.id
    subnet2 = azurerm_network_security_group.ssh.id
    subnet3 = azurerm_network_security_group.ssh.id
  }

  tags = {
    environment = "dev"
    costcenter  = "it"
  }
}

data "curl" "public_ip" {
  http_method = "GET"
  uri         = "https://api.ipify.org?format=json"
}

resource "azurerm_network_security_group" "ssh" {
  location            = azurerm_resource_group.example.location
  name                = "ssh"
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_network_security_rule" "example" {
  name                        = "AllowSSH"
  priority                    = 100
  protocol                   = "Tcp"
  destination_address_prefix = "*"
  destination_port_range     = "22"
  source_address_prefix      = jsondecode(data.curl.public_ip.response).ip
  source_port_range          = "*"
#  source_port_range = "0-65535"
  access                      = "Allow"
  direction                   = "Inbound"
  network_security_group_name = azurerm_network_security_group.ssh.name
  resource_group_name         = azurerm_resource_group.example.name
}
```

Apply this config, then change `source_port_range` will only affect `azurerm_network_security_rule` resource. Could anyone give me a minimum sample code that can reproduce this issue? Thanks.

**Comment by a-z-i-z** [comment] 2022-10-10 09:22
@lonegunmanb Can you check with the following code once as I was able to reproduce the re-creation of VNet if modifications done to NSG?

**vnet.tf**
```terraform
resource "azurerm_resource_group" "example" {
  location = "local.azure_region"
  name     = var.vnet_resource_group_name
}

module "vnet" {
  source  = "Azure/vnet/azurerm"
  version = "2.7.0"
  depends_on = [
    azurerm_resource_group.example,
    module.nsg_public_subnet_A,
    module.nsg_private_subnet_A
  ]

  vnet_name           = var.vnet_name
  address_space       = var.address_space
  resource_group_name = azurerm_resource_group.example.name
  subnet_names        = var.subnet_names
  subnet_prefixes     = var.subnet_prefixes
  tags                = local.tags

  nsg_ids = {
    element(var.subnet_names, 0) = module.nsg_public_subnet_A.network_security_group_id
    element(var.subnet_names, 1) = module.nsg_private_subnet_A.network_security_group_id
  }

  subnet_service_endpoints = {
    element(var.subnet_names, 0) = ["Microsoft.ContainerRegistry"]
    element(var.subnet_names, 1) = ["Microsoft.Sql"]
  }
}

module "nsg_public_subnet_A" {
  source  = "Azure/network-security-group/azurerm"
  version = "3.6.0"
  depends_on = [
    azurerm_resource_group.example
  ]

  security_group_name = "${element(var.subnet_names, 0)}-nsg"
  location            = local.azure_region
  resource_group_name = azurerm_resource_group.example.name
  tags                = local.tags

  custom_rules = [
    {
      name                       = "HTTP"
      priority                   = 100
      direction                  = "Inbound"
      access                     = "Allow"
      protocol                   = "Tcp"
      source_port_range          = "*"
      destination_port_range     = "80"
      source_address_prefix      = "*"
      destination_address_prefix = "*"
      description                = "Allow inbound HTTP access from all IPs."
    },
    {
      name                       = "HTTPS"
      priority                   = 101
      direction                  = "Inbound"
      access                     = "Allow"
      protocol                   = "Tcp"
      source_port_range          = "*"
      destination_port_range     = "443"
      source_address_prefix      = "*"
      destination_address_prefix = "*"
      description                = "Allow inbound HTTPS access from all IPs."
    },
    {
      name                       = "ApplicationGateway"
      priority                   = 102
      direction                  = "Inbound"
      access                     = "Allow"
      protocol                   = "Tcp"
      source_port_range          = "*"
      destination_port_range     = "65200-65535"
      source_address_prefix      = "GatewayManager"
      destination_address_prefix = "*"
      description                = "Allow inbound Application Gateway pre-requisite access."
    }
  ]
}

module "nsg_private_subnet_A" {
  source  = "Azure/network-security-group/azurerm"
  version = "3.6.0"
  depends_on = [
    azurerm_resource_group.example
  ]

  security_group_name = "${element(var.subnet_names, 1)}-nsg"
  location            = local.azure_region
  resource_group_name = azurerm_resource_group.example.name
  tags                = local.tags

  custom_rules = [
    {
      name                       = "MSSQL"
      priority                   = 100
      direction                  = "Inbound"
      access                     = "Allow"
      protocol                   = "Tcp"
      source_port_range          = "*"
      destination_port_range     = "1433"
      source_address_prefix      = element(var.subnet_prefixes, 0)
      destination_address_prefix = "*"
      description                = "Allow inbound MSSQL server access from public-subnet-A (Private IP)."
    }
  ]
}
```

**vnet.variables.tf**
```terraform
variable "vnet_resource_group_name" {
  type        = string
  description = "Azure resource group name."
  default     = "test-rg"

  validation {
    condition     = can(regex("-rg$", var.vnet_resource_group_name))
    error_message = "ERROR: Resource group name must end with \"-rg\"."
  }
}

variable "vnet_name" {
  type        = string
  description = "Name of the VNet to create."
  default     = "test-vnet"

  validation {
    condition     = can(regex("-vnet$", var.vnet_name))
    error_message = "ERROR: VNet name must end with \"-vnet\"."
  }
}

variable "address_space" {
  type        = list(string)
  description = "The address space that is used by the virtual network."
  default     = ["10.0.0.0/16"]
}

variable "subnet_names" {
  type        = list(string)
  description = "A list of subnets inside the VNet."
  default     = ["test-public-subnet-A", "test-private-subnet-A"]
}

variable "subnet_prefixes" {
  type        = list(string)
  description = "The address prefix to use for the subnet."
  default     = ["10.0.0.0/19", "10.0.32.0/19"]
}
```

**locals.tf**
```terraform
locals {
  azure_region = "West US 2"
  tags = {
    managed-by = "terraform"
  }
}
```

Once applied, modify any NSG rules and it would show to re-create VNet on next `terraform plan`.

**Comment by lonegunmanb** [comment] 2022-10-10 09:47
@a-z-i-z thanks for your reply, I'll try asap.

**Comment by lonegunmanb** [comment] 2022-10-11 01:14
Hello @a-z-i-z thanks for your sample, yeah I can reproduce this issue, and your case is easy to fix.

The re-creation is caused by the following code:

```hcl
resource "azurerm_virtual_network" "vnet" {
  address_space       = var.address_space
  location            = var.vnet_location != null ? var.vnet_location : data.azurerm_resource_group.vnet.location
```

If `var.vnet_location` is `null` then the code will use `data.azurerm_resource_group.vnet.location` as vnet's `location`, and `location` is a `ForceNew` argument. The generated plan showed:

```text
~ location                = "westus2" -> (known after apply) # forces replacement
```

Because the `data` will refresh everytime we plan or apply so the value is `known after apply`. In that case we just assign a static `vnet_location` to this module to solve this issue:

```hcl
module "vnet" {
  source     = "../../"
  depends_on = [
    azurerm_resource_group.example,
    module.nsg_public_subnet_A,
    module.nsg_private_subnet_A
  ]

  vnet_name           = var.vnet_name
  vnet_location       = local.azure_region
```

Please let me know if you have any further question on this issue, thanks.

**Comment by a-z-i-z** [comment] 2022-10-11 17:45
@lonegunmanb Thank you for your solution. Just thinking if `vnet_location` should be kept as one of the required parameters to avoid facing this issue ? Most of the time people tends to avoid `optional` parametes and go on with the depending/default values. In my case, VNet module depends on it's respective resource group location and which is why I want to avoid passing the same `location` parameter in VNet.

**Comment by lonegunmanb** [comment] 2022-10-13 00:51
Yes @a-z-i-z you're right. I'm working on a new Pr to do that, remove this whole datasource since it does more harm than benefit.

We have added an experimental CI pipeline to this module and we're adding more features into this pipeline. I'm working on a tool that can detect breaking changes by static analysis module's schema, once I finish this tool and add it into our pipeline, I'll continue this removal Pr. Thanks for your contribution, would you please close this issue? Or please feel free to ping me if you have any further questions.

**Comment by a-z-i-z** [comment] 2022-10-13 09:49
@lonegunmanb Thank you for your quick fix and taking this on priority. ✅

**Comment by lonegunmanb** [comment] 2022-10-14 01:34
I'm closing this issue but please feel free to open a new issue if you have encountered the same issue and `var.vnet_location` didn't work for you.

**Closed by lonegunmanb** 2022-10-14 01:34 UTC
